CIRCUITPY_WIFI_SSID = "YOUR_WIFI_NAME" 
CIRCUITPY_WIFI_PASSWORD = "YOUR_WIFI_PASSWORD" 
AIO_USERNAME = "YOUR_AIO_USERNAME" 
AIO_KEY = "YOUR_ADAFRUIT_AIO_KEY" 
TMBD_TOKEN = "your_tmdb_access_token" 
TMDB_KEY = "your_tmdb_key"